name: Profile README

on:
  schedule: [{cron: "0 0 * * *"}]  # every day at 00:00 UTC
  workflow_dispatch:  # allows manual triggering

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: joshmgross/guestbook@main
      with:
        issue: 1
        approvers: |
          unkokaeru
    - name: Update guestbook
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --local user.email "actions@github.com"
          git config --local user.name "${{ github.actor }}"
          git add README.md
          git commit -m "chore: update guestbook"
          git push
        fi
    - name: Update metrics (lines of code)
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.lines.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: repositories
        plugin_lines: yes
        plugin_lines_delay: 30
    - name: Update metrics (habits)
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.habits.charts.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_habits: yes
        plugin_habits_facts: yes
        plugin_habits_charts: yes
        plugin_habits_skipped: |
          bilbois
          quartz
          digital-garden
        config_timezone: Europe/London
    - name: Update metrics (wakatime)
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.wakatime.svg
        token: NOT_NEEDED
        base: ""
        plugin_wakatime: yes
        plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
        plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
    - name: Update metric (anime)
      uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.anilist.svg
        token: NOT_NEEDED
        base: ""
        plugin_anilist: yes
        plugin_anilist_medias: anime
        plugin_anilist_sections: favorites, watching, characters
        plugin_anilist_limit: 1
